import type { Brand, Product } from './types'

export const brands: Brand[] = [
  {
    id: 'dot-n-key',
    name: 'Dot n Key',
    desc: 'Skincare essentials',
    tagline: 'Science-backed formulas for radiant skin',
    image: '1785581778868-79100f7fe56c',
    color: '#EAE5DC',
  },
  {
    id: 'reginal-men',
    name: 'Reginal Men',
    desc: "Men's grooming",
    tagline: 'Precision grooming crafted for him',
    image: '1613803745799-ba6c10aace85',
    color: '#E4E0DA',
  },
  {
    id: 'palm',
    name: 'Palm',
    desc: 'Beauty essentials',
    tagline: 'Pure beauty, pure confidence',
    image: '1629380108599-ea06489d66f5',
    color: '#EDE8E0',
  },
  {
    id: 'flix',
    name: 'Flix',
    desc: 'Beauty & skincare',
    tagline: 'Glow on your own terms',
    image: '1631730486572-226d1f595b68',
    color: '#F0E8E4',
  },
  {
    id: 'mamaearth',
    name: 'Mamaearth',
    desc: 'Natural-inspired beauty',
    tagline: 'Toxin-free. Nature-loving. You.',
    image: '1598440947619-2c35fc9aa908',
    color: '#E5EDE5',
  },
  {
    id: 'derma',
    name: 'Derma',
    desc: 'Dermatological skincare',
    tagline: 'Clinically tested. Dermatologist approved.',
    image: '1772191530787-b9546da02fbc',
    color: '#E8E4ED',
  },
  {
    id: 'deconstruct',
    name: 'Deconstruct',
    desc: 'Minimal, science-led skincare',
    tagline: 'Smart formulas for everyday skin health',
    image: '1706612902117-8c3c5e3d7c50',
    color: '#E7EFEA',
  },
  {
    id: 'foxtale',
    name: 'Foxtale',
    desc: 'Modern skincare',
    tagline: 'Skincare, reimagined for today',
    image: '1665763630810-e6251bdd392d',
    color: '#EDE5E2',
  },
]

export const products: Product[] = [
  {
    id: 'dnk-1',
    brand: 'Dot n Key',
    brandId: 'dot-n-key',
    name: 'Vitamin C Brightening Serum',
    description: 'Brightens skin tone and reduces dark spots with 15% stabilised Vitamin C and Niacinamide complex.',
    price: 1990,
    originalPrice: 2490,
    rating: 4.7,
    reviews: 328,
    image: '1665763630810-e6251bdd392d',
    images: ['1665763630810-e6251bdd392d', '1785581778868-79100f7fe56c', '1772191530787-b9546da02fbc'],
    category: 'Serum',
    concern: ['Brightening', 'Hyperpigmentation'],
    isNew: true,
    inStock: true,
    benefits: ['Brightens dull skin tone', 'Reduces dark spots & hyperpigmentation', 'Boosts collagen synthesis', 'Antioxidant protection'],
    howToUse: 'Apply 2–3 drops on cleansed face. Gently pat until absorbed. Use morning and night before moisturiser.',
    ingredients: 'Ascorbic Acid 15%, Niacinamide 3%, Hyaluronic Acid, Ferulic Acid, Vitamin E',
  },
  {
    id: 'dnk-2',
    brand: 'Dot n Key',
    brandId: 'dot-n-key',
    name: 'Hyaluronic Acid Hydra Burst Moisturiser',
    description: 'Deep hydration moisturiser with multi-molecular Hyaluronic Acid that delivers 48 hours of moisture.',
    price: 1690,
    originalPrice: 1990,
    rating: 4.5,
    reviews: 215,
    image: '1772191530787-b9546da02fbc',
    images: ['1772191530787-b9546da02fbc', '1785581778868-79100f7fe56c'],
    category: 'Moisturiser',
    concern: ['Hydration', 'Dryness'],
    isNew: false,
    inStock: true,
    benefits: ['48-hour hydration', 'Plumps and smooths skin', 'Lightweight non-greasy formula', 'Suitable for all skin types'],
    howToUse: 'Apply on face and neck after toning. Use morning and evening.',
    ingredients: 'Hyaluronic Acid (High & Low MW), Ceramide NP, Panthenol, Allantoin',
  },
  {
    id: 'dnk-3',
    brand: 'Dot n Key',
    brandId: 'dot-n-key',
    name: 'SPF 50 Mineral Sunscreen Gel',
    description: 'Lightweight, non-whitening mineral sunscreen with blue light protection and antioxidants.',
    price: 1290,
    originalPrice: 1590,
    rating: 4.6,
    reviews: 412,
    image: '1785581778868-79100f7fe56c',
    images: ['1785581778868-79100f7fe56c'],
    category: 'Sunscreen',
    concern: ['Sun Care', 'Brightening'],
    isNew: true,
    inStock: true,
    benefits: ['SPF 50 PA++++', 'Zero white cast', 'Blue light protection', 'Antioxidant enriched'],
    howToUse: 'Apply generously 15 minutes before sun exposure. Reapply every 2–3 hours.',
    ingredients: 'Zinc Oxide, Titanium Dioxide, Niacinamide 5%, Centella Asiatica',
  },
  {
    id: 'dnk-4',
    brand: 'Dot n Key',
    brandId: 'dot-n-key',
    name: 'Retinol Night Repair Cream',
    description: 'Overnight repair cream with 0.1% Retinol and Peptides for visibly smoother skin by morning.',
    price: 2190,
    originalPrice: 2690,
    rating: 4.4,
    reviews: 189,
    image: '1613803745799-ba6c10aace85',
    images: ['1613803745799-ba6c10aace85'],
    category: 'Moisturiser',
    concern: ['Anti-aging', 'Brightening'],
    isNew: false,
    inStock: true,
    benefits: ['Reduces fine lines', 'Evens skin texture', 'Boosts cell renewal', 'Retinol + Peptide complex'],
    howToUse: 'Apply pea-sized amount on cleansed skin at night. Use 2–3 times per week initially.',
    ingredients: 'Retinol 0.1%, Matrixyl 3000, Shea Butter, Squalane, Bisabolol',
  },
  {
    id: 'me-1',
    brand: 'Mamaearth',
    brandId: 'mamaearth',
    name: 'Ubtan Face Wash with Turmeric',
    description: 'Natural face wash with turmeric and saffron extracts for a radiant, glowing complexion.',
    price: 349,
    originalPrice: 399,
    rating: 4.5,
    reviews: 1240,
    image: '1629380108599-ea06489d66f5',
    images: ['1629380108599-ea06489d66f5'],
    category: 'Cleanser',
    concern: ['Brightening', 'Cleansing'],
    isNew: false,
    inStock: true,
    benefits: ['Natural brightening', 'Deep cleansing', 'Toxin-free formula', 'Suitable for all skin types'],
    howToUse: 'Apply on wet face, massage in circular motions for 60 seconds, rinse thoroughly.',
    ingredients: 'Turmeric Extract, Saffron Extract, Aloe Vera, Glycerine',
  },
  {
    id: 'me-2',
    brand: 'Mamaearth',
    brandId: 'mamaearth',
    name: 'Tea Tree Face Serum',
    description: 'Acne-fighting serum with Tea Tree Oil and Salicylic Acid that targets breakouts at the source.',
    price: 599,
    originalPrice: 699,
    rating: 4.3,
    reviews: 876,
    image: '1598440947619-2c35fc9aa908',
    images: ['1598440947619-2c35fc9aa908'],
    category: 'Serum',
    concern: ['Acne Care', 'Cleansing'],
    isNew: true,
    inStock: true,
    benefits: ['Targets active breakouts', 'Reduces acne marks', 'Antibacterial formula', 'Oil-control'],
    howToUse: 'Apply 3–4 drops on affected areas after cleansing. Use morning and night.',
    ingredients: 'Tea Tree Oil 1%, Salicylic Acid 0.5%, Niacinamide 5%, Willow Bark Extract',
  },
  {
    id: 'me-3',
    brand: 'Mamaearth',
    brandId: 'mamaearth',
    name: 'Onion Hair Oil',
    description: 'Hair growth oil enriched with onion oil and redensyl to reduce hair fall.',
    price: 499,
    originalPrice: 599,
    rating: 4.6,
    reviews: 2340,
    image: '1782687633966-1ceb2a3fdf0f',
    images: ['1782687633966-1ceb2a3fdf0f'],
    category: 'Hair Care',
    concern: ['Hair Fall', 'Hair Growth'],
    isNew: false,
    inStock: true,
  },
  {
    id: 'fx-1',
    brand: 'Foxtale',
    brandId: 'foxtale',
    name: 'Dewy Skin Moisturiser SPF 25',
    description: 'Lightweight daily moisturiser with SPF 25 and ceramides for a healthy skin barrier.',
    price: 1495,
    originalPrice: 1795,
    rating: 4.8,
    reviews: 567,
    image: '1697201358649-ca8e6ecc3ac0',
    images: ['1697201358649-ca8e6ecc3ac0', '1785581778868-79100f7fe56c'],
    category: 'Moisturiser',
    concern: ['Hydration', 'Sun Care'],
    isNew: true,
    inStock: true,
    benefits: ['SPF 25 protection', 'Barrier strengthening ceramides', 'Dewy glass-skin finish', 'Non-comedogenic'],
    howToUse: 'Apply as the last step of your morning routine. Massage gently into skin.',
    ingredients: 'Ceramide NP, Ceramide AP, Cholesterol, Hyaluronic Acid, SPF 25',
  },
  {
    id: 'fx-2',
    brand: 'Foxtale',
    brandId: 'foxtale',
    name: 'Brightening Vitamin C Toner',
    description: 'Alcohol-free toner with 5% Niacinamide and Vitamin C for a clear, luminous complexion.',
    price: 995,
    originalPrice: 1195,
    rating: 4.6,
    reviews: 334,
    image: '1626897844971-aef92643f056',
    images: ['1626897844971-aef92643f056'],
    category: 'Toner',
    concern: ['Brightening', 'Acne Care'],
    isNew: false,
    inStock: true,
    benefits: ['Brightens skin', 'Minimises pores', 'Balances skin tone', 'Alcohol-free gentle formula'],
    howToUse: 'After cleansing, apply to cotton pad and sweep across face or press directly into skin.',
  },
  {
    id: 'dr-1',
    brand: 'Derma',
    brandId: 'derma',
    name: 'Ceramide Barrier Repair Cream',
    description: 'Clinically tested barrier repair cream with 3 essential ceramides and Madecassoside.',
    price: 2995,
    originalPrice: 3495,
    rating: 4.9,
    reviews: 234,
    image: '1772191530787-b9546da02fbc',
    images: ['1772191530787-b9546da02fbc', '1785581778868-79100f7fe56c'],
    category: 'Moisturiser',
    concern: ['Hydration', 'Sensitive Skin'],
    isNew: false,
    inStock: true,
    benefits: ['Restores skin barrier', 'Clinically tested for sensitive skin', 'Soothes redness', 'Dermatologist approved'],
    howToUse: 'Apply twice daily on cleansed skin. Safe for sensitive and reactive skin.',
    ingredients: 'Ceramide NP, Ceramide AP, Ceramide EOP, Madecassoside, Niacinamide',
  },
  {
    id: 'dr-2',
    brand: 'Derma',
    brandId: 'derma',
    name: 'AHA BHA Exfoliating Serum',
    description: 'Gentle chemical exfoliant with 10% AHA + 2% BHA for smooth, refined skin texture.',
    price: 2495,
    originalPrice: 2995,
    rating: 4.7,
    reviews: 178,
    image: '1665763630810-e6251bdd392d',
    images: ['1665763630810-e6251bdd392d'],
    category: 'Serum',
    concern: ['Brightening', 'Acne Care'],
    isNew: true,
    inStock: true,
    benefits: ['Unclogs pores', 'Smooths skin texture', 'Reduces blackheads', 'Boosts radiance'],
    howToUse: 'Use 2–3 times per week at night. Apply on cleansed dry skin, avoid eye area.',
    ingredients: 'Glycolic Acid 8%, Lactic Acid 2%, Salicylic Acid 2%, Aloe Vera, Panthenol',
  },
  {
    id: 'pl-1',
    brand: 'Palm',
    brandId: 'palm',
    name: 'Rose Glow Facial Oil',
    description: 'Luxurious facial oil with cold-pressed Rosehip, Jojoba, and Argan Oil for a radiant glow.',
    price: 1895,
    originalPrice: 2195,
    rating: 4.6,
    reviews: 145,
    image: '1782687633966-1ceb2a3fdf0f',
    images: ['1782687633966-1ceb2a3fdf0f'],
    category: 'Serum',
    concern: ['Hydration', 'Brightening'],
    isNew: true,
    inStock: true,
    benefits: ['Deep nourishment', 'Glow-boosting formula', 'Reduces fine lines', 'Absorbs quickly'],
    howToUse: 'Apply 3–4 drops on face after serum, massage gently. Use day or night.',
    ingredients: 'Rosehip Oil, Jojoba Oil, Argan Oil, Vitamin E, Bakuchiol',
  },
  {
    id: 'pl-2',
    brand: 'Palm',
    brandId: 'palm',
    name: 'Gentle Micellar Cleansing Water',
    description: 'Effortlessly removes makeup and impurities without stripping the skin barrier.',
    price: 895,
    originalPrice: 1095,
    rating: 4.4,
    reviews: 98,
    image: '1629380108599-ea06489d66f5',
    images: ['1629380108599-ea06489d66f5'],
    category: 'Cleanser',
    concern: ['Cleansing', 'Hydration'],
    isNew: false,
    inStock: true,
  },
  {
    id: 'fl-1',
    brand: 'Flix',
    brandId: 'flix',
    name: 'Glow Drops Highlighter Serum',
    description: 'Buildable glow drops with light-reflecting particles and Vitamin E for a lit-from-within look.',
    price: 1295,
    originalPrice: 1595,
    rating: 4.4,
    reviews: 267,
    image: '1631730486572-226d1f595b68',
    images: ['1631730486572-226d1f595b68'],
    category: 'Serum',
    concern: ['Brightening', 'Hydration'],
    isNew: false,
    inStock: true,
    benefits: ['Luminous glow', 'Buildable coverage', 'Skin-nourishing formula', 'Mix with moisturiser'],
    howToUse: 'Mix 1–2 drops with your moisturiser or apply directly on cheekbones for a glow.',
  },
  {
    id: 'fl-2',
    brand: 'Flix',
    brandId: 'flix',
    name: 'Hydrating Lip Serum',
    description: 'Plumping lip serum with Hyaluronic Acid and peptides for soft, defined lips.',
    price: 795,
    originalPrice: 995,
    rating: 4.5,
    reviews: 156,
    image: '1598440947619-2c35fc9aa908',
    images: ['1598440947619-2c35fc9aa908'],
    category: 'Lip Care',
    concern: ['Hydration'],
    isNew: true,
    inStock: true,
  },
  {
    id: 'rm-1',
    brand: 'Reginal Men',
    brandId: 'reginal-men',
    name: 'Anti-Pollution Charcoal Face Wash',
    description: "Men's charcoal face wash with activated charcoal and zinc for deep pore cleansing.",
    price: 549,
    originalPrice: 649,
    rating: 4.5,
    reviews: 389,
    image: '1613803745799-ba6c10aace85',
    images: ['1613803745799-ba6c10aace85'],
    category: 'Cleanser',
    concern: ['Cleansing', 'Acne Care'],
    isNew: false,
    inStock: true,
    benefits: ['Removes pollution particles', 'Deep pore cleansing', 'Controls excess oil', 'Refreshing gel formula'],
    howToUse: 'Apply on wet face, lather well, massage for 60 seconds, rinse thoroughly.',
    ingredients: 'Activated Charcoal, Zinc PCA, Salicylic Acid, Menthol',
  },
  {
    id: 'rm-2',
    brand: 'Reginal Men',
    brandId: 'reginal-men',
    name: 'Daily Defense Moisturiser SPF 30',
    description: "Lightweight men's moisturiser with SPF 30 and hyaluronic acid for all-day protection.",
    price: 895,
    originalPrice: 1095,
    rating: 4.6,
    reviews: 234,
    image: '1626897844971-aef92643f056',
    images: ['1626897844971-aef92643f056'],
    category: 'Moisturiser',
    concern: ['Sun Care', 'Hydration'],
    isNew: true,
    inStock: true,
    benefits: ['SPF 30 protection', 'Non-greasy finish', 'Hydrates for 8 hours', "Designed for men's skin"],
    howToUse: 'Apply evenly on cleansed face and neck. Use as final step in morning routine.',
    ingredients: 'Hyaluronic Acid, SPF 30, Niacinamide 4%, Caffeine, Allantoin',
  },
]

export const journalPosts = [
  {
    id: 1,
    category: 'Skincare Guide',
    title: '5 Steps to Build a Simple Skincare Routine',
    excerpt: 'Starting a skincare routine can feel overwhelming. Here are the five essential steps every beginner needs.',
    image: '1544717304-a2db4a7b16ee',
    date: 'Aug 8, 2026',
    readTime: '4 min read',
  },
  {
    id: 2,
    category: 'Expert Advice',
    title: 'How to Choose the Right Moisturiser for Your Skin Type',
    excerpt: 'Oily, dry, combination or sensitive — finding the right moisturiser is the cornerstone of healthy skin.',
    image: '1670201203116-26644750a726',
    date: 'Aug 5, 2026',
    readTime: '5 min read',
  },
  {
    id: 3,
    category: 'Beauty Essentials',
    title: 'Everyday Skincare Essentials Worth Investing In',
    excerpt: 'The products that deserve a permanent spot in your routine, across every skin type and budget.',
    image: '1581182800629-7d90925ad072',
    date: 'Aug 1, 2026',
    readTime: '6 min read',
  },
]

export const skincareConcerns = [
  { label: 'Hydration', icon: '💧' },
  { label: 'Acne Care', icon: '✦' },
  { label: 'Brightening', icon: '✦' },
  { label: 'Moisturizing', icon: '✦' },
  { label: 'Sun Care', icon: '☀' },
  { label: 'Cleansing', icon: '✦' },
  { label: "Men's Grooming", icon: '✦' },
]
